//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.0.0 (NJsonSchema v11.5.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    register(body: CreateUserCommand | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Auth/Register";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRegister(_response);
        });
    }

    protected processRegister(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    login(body: LoginUserCommand | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Auth/Login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLogin(_response);
        });
    }

    protected processLogin(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    refreshToken(body: UpdateUserRefreshTokenCommand | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Auth/RefreshToken";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRefreshToken(_response);
        });
    }

    protected processRefreshToken(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    createResume(body: ResumeCreateCommand | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Resume/CreateResume";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateResume(_response);
        });
    }

    protected processCreateResume(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    updateResume(body: ResumeUpdateCommand | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Resume/UpdateResume";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateResume(_response);
        });
    }

    protected processUpdateResume(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    removeResume(body: ResumeRemoveCommand | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Resume/RemoveResume";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "DELETE",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRemoveResume(_response);
        });
    }

    protected processRemoveResume(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export interface CertificatesInfoDto {
    name?: string | undefined;
    link?: string | undefined;
}

export interface CreateUserCommand {
    userName?: string | undefined;
    email?: string | undefined;
    password?: string | undefined;
}

export interface EducationInfoDto {
    colleageName?: string | undefined;
    departmantAndMajor?: string | undefined;
    grade?: string | undefined;
    gpa?: number | undefined;
}

export interface JobDescriptionDto {
    description?: string | undefined;
}

export interface JobHistoryDto {
    role?: string | undefined;
    startEndPeriod?: string | undefined;
    company?: string | undefined;
    jobDescriptionDtos?: JobDescriptionDto[] | undefined;
}

export interface LoginUserCommand {
    userNameOrEmail?: string | undefined;
    password?: string | undefined;
}

export interface ProjectDefinitionsDto {
    explaining?: string | undefined;
}

export interface ProjectsInfoDto {
    name?: string | undefined;
    link?: string | undefined;
    projectDefinitionsDtos?: ProjectDefinitionsDto[] | undefined;
}

export interface ResumeCreateCommand {
    saveResumeDto?: SaveResumeDto;
}

export interface ResumeRemoveCommand {
    resumeId?: string;
}

export interface ResumeUpdateCommand {
    resumeId?: string;
    saveResumeDto?: SaveResumeDto;
}

export interface SaveResumeDto {
    name?: string | undefined;
    surname?: string | undefined;
    email?: string | undefined;
    cellPhone?: number | undefined;
    location?: string | undefined;
    githubLink?: string | undefined;
    linkedinLink?: string | undefined;
    autobiography?: string | undefined;
    skillCategoryDtos?: SkillCategoryDto[] | undefined;
    jobHistoryDtos?: JobHistoryDto[] | undefined;
    educationInfoDtos?: EducationInfoDto[] | undefined;
    projectsInfoDtos?: ProjectsInfoDto[] | undefined;
    volunteerInfoDtos?: VolunteerInfoDto[] | undefined;
    certificatesInfoDtos?: CertificatesInfoDto[] | undefined;
}

export interface SkillCategoryDto {
    name?: string | undefined;
    skills?: SkillDto[] | undefined;
}

export interface SkillDto {
    technology?: string | undefined;
    level?: string | undefined;
}

export interface UpdateUserRefreshTokenCommand {
    refreshToken?: string | undefined;
}

export interface VolunteerDescriptionDto {
    explaining?: string | undefined;
}

export interface VolunteerInfoDto {
    role?: string | undefined;
    company?: string | undefined;
    year?: number;
    volunteerDescriptionDtos?: VolunteerDescriptionDto[] | undefined;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}