//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    register(body: CreateUserCommand | undefined): Promise<BooleanServiceResult> {
        let url_ = this.baseUrl + "/api/Auth/Register";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRegister(_response);
        });
    }

    protected processRegister(response: Response): Promise<BooleanServiceResult> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BooleanServiceResult;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BooleanServiceResult>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    login(body: LoginUserCommand | undefined): Promise<TokenInformationDtoServiceResult> {
        let url_ = this.baseUrl + "/api/Auth/Login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLogin(_response);
        });
    }

    protected processLogin(response: Response): Promise<TokenInformationDtoServiceResult> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as TokenInformationDtoServiceResult;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TokenInformationDtoServiceResult>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    refreshToken(body: UpdateUserRefreshTokenCommand | undefined): Promise<RefreshTokenInformationDtoServiceResult> {
        let url_ = this.baseUrl + "/api/Auth/RefreshToken";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRefreshToken(_response);
        });
    }

    protected processRefreshToken(response: Response): Promise<RefreshTokenInformationDtoServiceResult> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as RefreshTokenInformationDtoServiceResult;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<RefreshTokenInformationDtoServiceResult>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    createResumeSub(body: CreateResumeCommand | undefined): Promise<BooleanServiceResult> {
        let url_ = this.baseUrl + "/api/Resume/CreateResumeSub";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateResumeSub(_response);
        });
    }

    protected processCreateResumeSub(response: Response): Promise<BooleanServiceResult> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BooleanServiceResult;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BooleanServiceResult>(null as any);
    }

    /**
     * @return OK
     */
    getAllResume(): Promise<ResumeDtoListServiceResult> {
        let url_ = this.baseUrl + "/api/Resume/GetAllResume";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAllResume(_response);
        });
    }

    protected processGetAllResume(response: Response): Promise<ResumeDtoListServiceResult> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ResumeDtoListServiceResult;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ResumeDtoListServiceResult>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    updateResume(body: UpdateResumeCommand | undefined): Promise<BooleanServiceResult> {
        let url_ = this.baseUrl + "/api/Resume/UpdateResume";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateResume(_response);
        });
    }

    protected processUpdateResume(response: Response): Promise<BooleanServiceResult> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BooleanServiceResult;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BooleanServiceResult>(null as any);
    }

    /**
     * @param resumeSubId (optional) 
     * @return OK
     */
    removeResume(resumeSubId: string | undefined): Promise<BooleanServiceResult> {
        let url_ = this.baseUrl + "/api/Resume/RemoveResume?";
        if (resumeSubId === null)
            throw new Error("The parameter 'resumeSubId' cannot be null.");
        else if (resumeSubId !== undefined)
            url_ += "ResumeSubId=" + encodeURIComponent("" + resumeSubId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRemoveResume(_response);
        });
    }

    protected processRemoveResume(response: Response): Promise<BooleanServiceResult> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BooleanServiceResult;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BooleanServiceResult>(null as any);
    }
}

export interface BooleanServiceResult {
    isSuccess?: boolean;
    message?: string | undefined;
    errors?: string[] | undefined;
    data?: boolean;
}

export interface CreateResumeCommand {
    resumeTitle?: string | undefined;
}

export interface CreateUserCommand {
    userName?: string | undefined;
    email?: string | undefined;
    password?: string | undefined;
}

export interface LoginUserCommand {
    userNameOrEmail?: string | undefined;
    password?: string | undefined;
}

export interface RefreshTokenInformationDto {
    refreshToken?: string | undefined;
}

export interface RefreshTokenInformationDtoServiceResult {
    isSuccess?: boolean;
    message?: string | undefined;
    errors?: string[] | undefined;
    data?: RefreshTokenInformationDto;
}

export interface ResumeDto {
    id?: string;
    resumeTitle?: string | undefined;
    companies?: string | undefined;
}

export interface ResumeDtoListServiceResult {
    isSuccess?: boolean;
    message?: string | undefined;
    errors?: string[] | undefined;
    data?: ResumeDto[] | undefined;
}

export interface TokenInformationDto {
    accessToken?: string | undefined;
    refreshToken?: string | undefined;
    expirationDatetime?: Date;
}

export interface TokenInformationDtoServiceResult {
    isSuccess?: boolean;
    message?: string | undefined;
    errors?: string[] | undefined;
    data?: TokenInformationDto;
}

export interface UpdateResumeCommand {
    resumeSubId?: string | undefined;
    resumeTitle?: string | undefined;
    companies?: string | undefined;
}

export interface UpdateUserRefreshTokenCommand {
    refreshToken?: string | undefined;
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}